apiVersion: v1
data:
  react_app_server_port: "8081"
  REACT_APP_GAMES_INFO_URL: route-info-labproj08.apps.ocp.lab.cloudpak.site 
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: cmap-gry