apiVersion: apps/v1
kind: Deployment
metadata:
  name: module-gry
  labels:
    app: module-gry
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: module-gry
      version: v1
  template:
    metadata:
      labels:
        app: module-gry
        version: v1
    spec:
      serviceAccountName: default
      containers:
      - name: module-gry
        image: image-registry.openshift-image-registry.svc:5000/labproj08/module-gry:0.0.3
        imagePullPolicy: Always
        env:
          - name: REACT_APP_GAMES_INFO_URL
            value: route-info-labproj08.apps.ocp.lab.cloudpak.site
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-credentials
                key: rootpasswd
        ports:
        - containerPort: 8081
        resources: {}
        envFrom:
        - configMapRef:
            name: cmap-gry
status: {}